/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_wlu_cs_levy_breezyslam_components_Map */

#ifndef _Included_edu_wlu_cs_levy_breezyslam_components_Map
#define _Included_edu_wlu_cs_levy_breezyslam_components_Map
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_wlu_cs_levy_breezyslam_components_Map
 * Method:    init
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_edu_wlu_cs_levy_breezyslam_components_Map_init
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     edu_wlu_cs_levy_breezyslam_components_Map
 * Method:    update
 * Signature: (Ledu/wlu/cs/levy/breezyslam/components/Scan;DDDID)V
 */
JNIEXPORT void JNICALL Java_edu_wlu_cs_levy_breezyslam_components_Map_update
  (JNIEnv *, jobject, jobject, jdouble, jdouble, jdouble, jint, jdouble);

/*
 * Class:     edu_wlu_cs_levy_breezyslam_components_Map
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_wlu_cs_levy_breezyslam_components_Map_toString
  (JNIEnv *, jobject);

/*
 * Class:     edu_wlu_cs_levy_breezyslam_components_Map
 * Method:    get
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_edu_wlu_cs_levy_breezyslam_components_Map_get
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_wlu_cs_levy_breezyslam_components_Map
 * Method:    reset
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_edu_wlu_cs_levy_breezyslam_components_Map_reset
  (JNIEnv *, jobject, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
