/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_wlu_cs_levy_breezyslam_components_Scan */

#ifndef _Included_edu_wlu_cs_levy_breezyslam_components_Scan
#define _Included_edu_wlu_cs_levy_breezyslam_components_Scan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_wlu_cs_levy_breezyslam_components_Scan
 * Method:    init
 * Signature: (IIDDDID)V
 */
JNIEXPORT void JNICALL Java_edu_wlu_cs_levy_breezyslam_components_Scan_init
  (JNIEnv *, jobject, jint, jint, jdouble, jdouble, jdouble, jint, jdouble);

/*
 * Class:     edu_wlu_cs_levy_breezyslam_components_Scan
 * Method:    toString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_wlu_cs_levy_breezyslam_components_Scan_toString
  (JNIEnv *, jobject);

/*
 * Class:     edu_wlu_cs_levy_breezyslam_components_Scan
 * Method:    update
 * Signature: ([IDDD)V
 */
JNIEXPORT void JNICALL Java_edu_wlu_cs_levy_breezyslam_components_Scan_update
  (JNIEnv *, jobject, jintArray, jdouble, jdouble, jdouble);

/*
 * Class:     edu_wlu_cs_levy_breezyslam_components_Scan
 * Method:    getobstcnt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_wlu_cs_levy_breezyslam_components_Scan_getobstcnt
  (JNIEnv *, jobject);

/*
 * Class:     edu_wlu_cs_levy_breezyslam_components_Scan
 * Method:    getcnt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_edu_wlu_cs_levy_breezyslam_components_Scan_getcnt
  (JNIEnv *, jobject);

/*
 * Class:     edu_wlu_cs_levy_breezyslam_components_Scan
 * Method:    getpoints
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_edu_wlu_cs_levy_breezyslam_components_Scan_getpoints
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
